### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/wchristie/.config/pbnh/config.yml'

### ISSUE THREAD

**Issue by wadechristie** [bhanderson/pbnh#25]
Checkout: 0b00bc5e32ab98c4d94f96ffd175ff975e3ae07e

Setup:
```
$ git clone git@github.com:wadechristie/pbnh.git
$ cd pbnh; virtualenv --python=python3 venv; source venv/bin/activate
$ pip install -r requirements.txt
````

Error:
```
$ python -m pbnh.run
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wchristie/opt/pbnh/pbnh/run.py", line 1, in <module>
    from pbnh.app import app
  File "/home/wchristie/opt/pbnh/pbnh/app/__init__.py", line 4, in <module>
    from pbnh.app import views
  File "/home/wchristie/opt/pbnh/pbnh/app/views.py", line 12, in <module>
    from pbnh.app import util
  File "/home/wchristie/opt/pbnh/pbnh/app/util.py", line 11, in <module>
    config = conf.get_config().get('database')
  File "/home/wchristie/opt/pbnh/pbnh/conf.py", line 6, in get_config
    with open (path) as config:
FileNotFoundError: [Errno 2] No such file or directory: '/home/wchristie/.config/pbnh/config.yml'
```

**Comment by jetpacktuxedo** [comment]
Sounds like you skipped `cp sample config.yml ~/.config/pbnh/config.yml`
